data-id="{{ $products->id }}"
data-barcode="{{ $products->barcode }}"
data-nama="{{ $products->nama }}"
data-harga="{{ $products->presentPrice() }}"
data-deskripsi="{{ $products->deskripsi }}"
data-gambar="{{ $products->url_gambar }}"
